[project]
name = "ismail"
version = "0.1.0"
description = "This is an Ai tool that translates Arabic Friday Jummah sermons to English in real-time."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
